<?php
namespace app\models\_base;
use app\components\AMapper;
use yii\data\ActiveDataProvider;
use Yii;
/**
 * This is the model base class for the table "issue".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Issue".
 *
 * Columns in table "issue" available as properties of the model,
 * followed by relations of table "issue" available as properties of the model.
 *
 * @property string $id
 * @property string $issue_name
 * @property string $issue_type
 * @property string $created
 * @property integer $creator
 * @property integer $reply
 * @property string $attached_table
 * @property string $attached_id
 */
abstract class BaseIssue extends AMapper {

    public static function tableName()
    {
        return 'issue';
    }

	public static function label($n = 1) {
		return Yii::t('app', 'Issue|Issues', $n);
	}

	public static function representingColumn() {
		return 'issue_name';
	}

    public function getIssueOperationHistories(){
        return $this->hasMany('IssueOperationHistory',['issue_id'=>'id']);
    }

	public function pivotModels() {
		return array(
		);
	}

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['guid', 'name', 'type', 'creator', 'attached_table', 'attached_id', 'assignee_company_table', 'created', 'modified'], 'required'],
            [['creator', 'attached_id', 'creator_company_id', 'assignee_id', 'assignee_company_id'], 'integer'],
            [['attached_data', 'current_state', 'issue_from', 'priority'], 'string'],
            [['press_date', 'created', 'modified'], 'safe'],
            [['guid'], 'string', 'max' => 64],
            [['name'], 'string', 'max' => 255],
            [['type', 'attached_table', 'assignee_company_table'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'guid' => 'Guid',
            'name' => 'Name',
            'type' => 'Type',
            'creator' => 'Creator',
            'attached_table' => 'Attached Table',
            'attached_id' => 'Attached ID',
            'attached_data' => 'Attached Data',
            'press_date' => 'Press Date',
            'current_state' => 'Current State',
            'issue_from' => 'Issue From',
            'creator_company_id' => 'Creator Company ID',
            'assignee_id' => 'Assignee ID',
            'assignee_company_id' => 'Assignee Company ID',
            'assignee_company_table' => 'Assignee Company Table',
            'priority' => 'Priority',
            'created' => 'Created',
            'modified' => 'Modified',
        ];
    }
    public function customFields()
    {
        return array(
            'id' => array( 'type' => 'textField', 'htmlOptions'=>array(  'size'=>10,'maxlength'=>10 ),  ),
            'issue_name' => array( 'type' => 'textField', 'htmlOptions'=>array(  'size'=>60,'maxlength'=>255 ),  ),
            'issue_type' => array( 'type' => 'textField', 'htmlOptions'=>array(  'size'=>56,'maxlength'=>56 ),  ),
            'created' => array( 'type' => 'textField', 'htmlOptions'=>array( ),  ),
            'creator' => array( 'type' => 'textField', 'htmlOptions'=>array( ),  ),
            'reply' => array( 'type' => 'textField', 'htmlOptions'=>array( ),  ),
            'attached_table' => array( 'type' => 'textField', 'htmlOptions'=>array(  'size'=>56,'maxlength'=>56 ),  ),
            'attached_id' => array( 'type' => 'textField', 'htmlOptions'=>array(  'size'=>10,'maxlength'=>10 ),  ),
        );
    }
    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search()
    {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.
        $query = $this::find()->where(
            [
                'id'=>$this->id,
                'name'=>$this->name,
                'type'=>$this->type,
                'creator'=>$this->creator,
                'attached_table'=>$this->attached_table,
                'attached_id'=>$this->attached_id,
                'attached_data'=>$this->attached_data,
                'press_date'=>$this->press_date,
                'current_state'=>$this->current_state,
                'issue_from'=>$this->issue_from,
                'assignee_id'=>$this->assignee_id,
                'assignee_company_id'=>$this->assignee_company_id,
                'assignee_company_table'=>$this->assignee_company_table,
                'priority'=>$this->priority,
                'created'=>$this->created,
                'modified'=>$this->modified
        ]);
        return new ActiveDataProvider([
            'query'=>$query,
        ]);
    }
}